Header header

float64[13] desired_joint_accelerations
float64[13] joint_velocity_induced_accelerations_upper_limit
float64[13] joint_velocity_induced_accelerations_lower_limit
float64[13] joint_position_induced_accelerations_upper_limit
float64[13] joint_position_induced_accelerations_lower_limit
float64[13] joint_positions_upper_limit
float64[13] joint_positions_lower_limit
float64[13] joint_velocities_upper_limit
float64[13] joint_velocities_lower_limit

float64[6] shovel_target_acceleration
float64[6] endeffector_target_acceleration
float64[6] endeffector_resulting_acceleration
float64[3] manipulator_base_target_acceleration
